// import { PrismaClient } from "@prisma/client";
import useSWR from 'swr'
import { getLocationOrigin } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from '../../styles/boxes.module.css'
// import prisma from "../prisma/seed";
// export async function getServerSideProps() {
//     console.log("backend");
//   const prisma = new PrismaClient();
//   let content = await prisma.news.findMany({});
//   for (const n of content) {
//     n.release_date = n.release_date.toString();
//   }
//   console.log(content);
//   return {
//     props: {
//       content,
//     },
//   };
// }

export default function MainLayout() {
  const { data, error } = useSWR('/api/v1/news');

    console.log(data, error);

    if (error) return "An error has occurred.";
    if (!data) return "Loading...";

  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">News</a>!
        </h1>

        <p className={styles.description}>News for You!</p>

        <div id="newsarray" className={styles.grid}>
              <div key={data.news[0].id}>
                <h2>{data.news[0].news_title}</h2>
                <p>{data.news[0].news_content}</p>
            </div>

            <div key={data.news[1].id}>
                <h2>{data.news[1].news_title}</h2>
                <p>{data.news[1].news_content}</p>
            </div>
        </div>

        <div>
          <button
            onClick={() => {
              window.location.href = "/login-panel";
            }}
          >
            Log In
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
